Repository Monofony/SymfonyStarter, pull requests merged in 2019-03, with the labels that each got.

#132 Move DotEnv on prod requirements
  composer.json
  composer.lock
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/test-prod-requirements
Labels: bug

#136 Fix setup command
  src/Command/Installer/SetupCommand.php
Labels: bug

#149 upgrade twig (security fix)
  composer.json
  composer.lock
Labels: bug

#150 Init a documentation to configure your datafixtures
  docs/cookbook/fixtures/factory.rst
  docs/cookbook/fixtures/fixture.rst
  docs/cookbook/fixtures/load.rst
  docs/cookbook/fixtures/map.rst.inc
  docs/cookbook/fixtures/suite.rst
  docs/cookbook/index.rst
Labels: Documentation

#148 improve listeners' dependency injection
  config/services.yaml
  config/services/listener.yml
Labels: DX

#151 improve data fixtures documentation
  docs/cookbook/entities/configure-your-routes.rst
  docs/cookbook/entities/first-resource.rst
  docs/cookbook/entities/manage-your-entity.rst
  docs/cookbook/fixtures/factory.rst
  docs/cookbook/fixtures/fixture.rst
  docs/cookbook/fixtures/load.rst
  docs/cookbook/fixtures/map.rst.inc
  docs/cookbook/fixtures/suite.rst
Labels: Documentation

#152 run setup command on install command
  src/Command/Installer/InstallCommand.php
Labels: Bug

#154 Refresh entities documentation
  docs/cookbook/entities/configure-your-routes.rst
  docs/cookbook/entities/first-resource.rst
  docs/cookbook/entities/manage-your-entity.rst
Labels: Documentation

#155 Makefile
  .gitignore
  Makefile.dist
Labels: DX

#156 Set username on admin user example factory
  src/Fixture/Factory/AdminUserExampleFactory.php
Labels: Enhancement

#157 [Docs] Specify your entities with phpspec
  docs/cookbook/bdd/how-to-configure-phpspec-with-code-coverage.rst
  docs/cookbook/bdd/how-to-design-entities-with-phpspec.rst
  docs/cookbook/bdd/how-to-disable-phpspec-code-coverage.rst
  docs/cookbook/bdd/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#158 [docs] design services with phpspec
  docs/cookbook/bdd/how-to-design-services-with-phpspec.rst
  docs/cookbook/bdd/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#159 Add test-behat-with-javascript command on makefile
  Makefile.dist
Labels: DX

#160 [docs] add it has no title by default behaviour on docs
  docs/cookbook/bdd/how-to-design-entities-with-phpspec.rst
Labels: Documentation

#161 Improve user and customer entities
  spec/App/Entity/AdminUserSpec.php
  spec/App/Entity/AppUserSpec.php
  spec/App/Entity/CustomerSpec.php
  src/Entity/AdminUser.php
  src/Entity/AdminUserInterface.php
  src/Entity/AppUser.php
  src/Entity/AppUserInterface.php
  src/Entity/Customer.php
  src/Entity/CustomerInterface.php
Labels: Enhancement

#162 improve infection
  infection.json.dist
  spec/App/Form/Extension/CustomerTypeExtensionSpec.php
  spec/App/Form/Extension/DateTypeExtensionSpec.php
Labels: DX

#163 Run infection only on changed files
  etc/travis/suites/application/script/test-infection
Labels: DX

#166 Autoconfigure frontend behat pages
  src/Behat/Resources/config/services/pages/frontend.yml
  src/Behat/Resources/config/services/pages/frontend/account.yml
Labels: Behat, DX

#167 [Composer] Fix project name and licence
  composer.json
  composer.lock
Labels: Bug

#168 Dump env prod
  .env
  composer.json
  composer.lock
  etc/capistrano/deploy.rb
Labels: Enhancement
