Repository Monofony/SymfonyStarter, pull requests merged in 2019-11, with the labels that each got.

#218 Add phpspec extension for phpstan
  composer.json
  composer.lock
  phpstan.neon
  symfony.lock
Labels: DX

#219 Update htaccess for Symfony 4
  public/.htaccess
Labels: Bug

#222 Fix Symfony security issues
  composer.lock
Labels: Bug

#226 Fix capistrano linked files
  etc/capistrano/deploy.rb
Labels: Bug

#227 Fix capistrano locking version and gem dependencies
  Gemfile
  etc/capistrano/deploy.rb
Labels: Maintenance

#229 Improve demo links on readme
  README.md
Labels: Documentation
