Repository Monofony/SymfonyStarter, pull requests merged in 2019-05, with the labels that each got.

#178 improve code quality on managing customers and registration behat con…
  src/Behat/Context/Ui/Backend/ManagingCustomersContext.php
  src/Behat/Context/Ui/Frontend/RegistrationContext.php
Labels: Behat, Enhancement

#181 Fix typo yaml
  docs/cookbook/entities/manage-your-entity.rst
Labels: Bug, Documentation

#180 Using vimeo psalm on test (level 8)
  composer.json
  composer.lock
  etc/travis/suites/application/script.sh
  etc/travis/suites/application/script/test-psalm
  psalm.xml
  src/Behat/Behaviour/Toggles.php
  src/Behat/Context/Cli/CommandContext.php
  src/Behat/Context/Cli/DefaultContext.php
  src/Behat/Context/Cli/InstallerContext.php
  src/Behat/Context/Hook/DoctrineORMContext.php
  src/Behat/Context/Setup/AdminSecurityContext.php
  src/Behat/Context/Setup/AdminUserContext.php
  src/Behat/Context/Setup/AppSecurityContext.php
  src/Behat/Context/Setup/CustomerContext.php
  src/Behat/Context/Setup/UserContext.php
  src/Behat/Context/Transform/CustomerContext.php
  src/Behat/Context/Ui/Backend/ManagingAdministratorsContext.php
  src/Behat/Context/Ui/Backend/ManagingCustomersContext.php
  src/Behat/Context/Ui/Backend/NotificationContext.php
  src/Behat/Context/Ui/EmailContext.php
  src/Behat/Context/Ui/Frontend/AccountContext.php
  src/Behat/Context/Ui/Frontend/LoginContext.php
  src/Behat/Context/Ui/Frontend/RegistrationContext.php
  src/Behat/Page/Backend/Administrator/CreatePage.php
  src/Behat/Page/Backend/Administrator/UpdatePage.php
  src/Behat/Page/Backend/Crud/CreatePage.php
  src/Behat/Page/Backend/Customer/IndexPage.php
  src/Behat/Page/Backend/Customer/UpdatePage.php
  src/Behat/Page/Frontend/Account/ChangePasswordPage.php
  src/Behat/Page/Frontend/Account/DashboardPage.php
  src/Behat/Page/Frontend/Account/LoginPage.php
  src/Behat/Page/Frontend/Account/ProfileUpdatePage.php
  src/Behat/Page/Frontend/Account/RegisterPage.php
  src/Behat/Page/Frontend/Account/RequestPasswordResetPage.php
  src/Behat/Page/Frontend/Account/ResetPasswordPage.php
  src/Behat/Page/Frontend/Account/VerificationPage.php
  src/Behat/Service/SecurityService.php
  src/Behat/Service/SharedSecurityService.php
  src/Command/Helper/EnsureDirectoryExistsAndIsWritable.php
  src/DependencyInjection/Compiler/ServicesPass.php
  src/EventListener/CanonicalizerListener.php
  src/EventListener/DefaultUsernameORMListener.php
  src/EventListener/PasswordUpdaterListener.php
  src/Fixture/Factory/AppUserExampleFactory.php
  src/Form/EventSubscriber/AddUserFormSubscriber.php
  src/Form/EventSubscriber/CustomerRegistrationFormSubscriber.php
  src/Installer/Checker/CommandDirectoryChecker.php
  symfony.lock
Labels: DX

#186 Upgrade sylius bundles and components
  composer.json
  composer.lock
Labels: Maintenance

#184 Add how to generate backend menu. Add article form type
  docs/cookbook/entities/configure-backend-menu.rst
  docs/cookbook/entities/first-resource.rst
  docs/cookbook/entities/map.rst.inc
  docs/cookbook/index.rst
Labels: Documentation

#188 Kill mutants
  composer.json
  composer.lock
  spec/App/Entity/AdminUserSpec.php
  spec/App/Form/EventSubscriber/AddUserFormSubscriberSpec.php
  spec/App/Form/Extension/DateTypeExtensionSpec.php
Labels: Enhancement

#190 Fix grid security issue
  composer.lock
Labels: Bug
